#include "iGeom_FCDefs.h"
#ifdef IGEOM_FC_FUNC_

#define iGeom_getDescription IGEOM_FC_FUNC_( igeom_getdescription, IGEOM_GETDESCRIPTION )
#define iGeom_newGeom IGEOM_FC_FUNC_( igeom_newgeom, IGEOM_NEWGEOM )
#define iGeom_save IGEOM_FC_FUNC_( igeom_save, IGEOM_SAVE )
#define iGeom_getRootSet IGEOM_FC_FUNC_( igeom_getrootset, IGEOM_GETROOTSET )
#define iGeom_getEntities IGEOM_FC_FUNC_( igeom_getentities, IGEOM_GETENTITIES )
#define iGeom_getNumOfType IGEOM_FC_FUNC_( igeom_getnumoftype, IGEOM_GETNUMOFTYPE )
#define iGeom_getEntBoundBox IGEOM_FC_FUNC_( igeom_getentboundbox, IGEOM_GETENTBOUNDBOX )
#define iGeom_copyEnt IGEOM_FC_FUNC_( igeom_copyent, IGEOM_COPYENT )
#define iGeom_deleteEnt IGEOM_FC_FUNC_( igeom_deleteent, IGEOM_DELETEENT )
#define iGeom_createSphere IGEOM_FC_FUNC_( igeom_createsphere, IGEOM_CREATESPHERE )
#define iGeom_createBrick IGEOM_FC_FUNC_( igeom_createbrick, IGEOM_CREATEBRICK )
#define iGeom_createCylinder IGEOM_FC_FUNC_( igeom_createcylinder, IGEOM_CREATECYLINDER )
#define iGeom_createCone IGEOM_FC_FUNC_( igeom_createcone, IGEOM_CREATECONE )
#define iGeom_createTorus IGEOM_FC_FUNC_( igeom_createtorus, IGEOM_CREATETORUS )
#define iGeom_moveEnt IGEOM_FC_FUNC_( igeom_moveent, IGEOM_MOVEENT )
#define iGeom_rotateEnt IGEOM_FC_FUNC_( igeom_rotateent, IGEOM_ROTATEENT )
#define iGeom_reflectEnt IGEOM_FC_FUNC_( igeom_reflectent, IGEOM_REFLECTENT )
#define iGeom_scaleEnt IGEOM_FC_FUNC_( igeom_scaleent, IGEOM_SCALEENT )
#define iGeom_uniteEnts IGEOM_FC_FUNC_( igeom_uniteents, IGEOM_UNITEENTS )
#define iGeom_subtractEnts IGEOM_FC_FUNC_( igeom_subtractents, IGEOM_SUBTRACTENTS )
#define iGeom_intersectEnts IGEOM_FC_FUNC_( igeom_intersectents, IGEOM_INTERSECTENTS )
#define iGeom_sectionEnt IGEOM_FC_FUNC_( igeom_sectionent, IGEOM_SECTIONENT )
#define iGeom_imprintEnts IGEOM_FC_FUNC_( igeom_imprintents, IGEOM_IMPRINTENTS )
#define iGeom_mergeEnts IGEOM_FC_FUNC_( igeom_mergeents, IGEOM_MERGEENTS )
#define iGeom_createEntSet IGEOM_FC_FUNC_( igeom_createentset, IGEOM_CREATEENTSET )
#define iGeom_addEntToSet IGEOM_FC_FUNC_( igeom_addenttoset, IGEOM_ADDENTTOSET )
#define iGeom_getTagSizeBytes IGEOM_FC_FUNC_( igeom_gettagsizebytes, IGEOM_GETTAGSIZEBYTES )
#define iGeom_getTagHandle IGEOM_FC_FUNC_( igeom_gettaghandle, IGEOM_GETTAGHANDLE )
#define iGeom_setEntSetData IGEOM_FC_FUNC_( igeom_setentsetdata, IGEOM_SETENTSETDATA )
#define iGeom_setEntSetIntData IGEOM_FC_FUNC_( igeom_setentsetintdata, IGEOM_SETENTSETINTDATA )
#define iGeom_setData IGEOM_FC_FUNC_( igeom_setdata, IGEOM_SETDATA )

#endif
